//
// Created by ub1404 on 15. 9. 8.
//

#ifndef UR_ROBOT_CONSTRAINEDMODEINTERFACE_H
#define UR_ROBOT_CONSTRAINEDMODEINTERFACE_H


class ConstrainedModeInterface {

};


#endif //UR_ROBOT_CONSTRAINEDMODEINTERFACE_H
